import { PrismaClient } from '@prisma/client';
const db=new PrismaClient();
async function main(){
 await db.project.upsert({where:{slug:'smart-energy-monitoring'},update:{},create:{title:'Smart Energy Monitoring',slug:'smart-energy-monitoring',excerpt:'IoT-based energy monitoring and billing concept.',content:'A smart energy platform combining sensors, dashboards, analytics and automated billing workflows.',technologies:'ESP32, IoT, Laravel, React',featured:true}});
 await db.project.upsert({where:{slug:'ai-real-estate-automation'},update:{},create:{title:'AI Real Estate Automation',slug:'ai-real-estate-automation',excerpt:'AI-assisted lead qualification and WhatsApp automation.',content:'An automation concept connecting CRM, AI agents, messaging and lead intelligence.',technologies:'n8n, AI, WhatsApp, CRM',featured:true}});
 await db.blogPost.upsert({where:{slug:'secure-small-enterprise-network'},update:{},create:{title:'Secure Small Enterprise Network',slug:'secure-small-enterprise-network',excerpt:'Practical architecture for building a secure small enterprise network.',content:'Network segmentation, firewall security, VPN, monitoring and access control.',category:'Networking',tags:'Network, Firewall, Security, VPN'}});
 await db.blogPost.upsert({where:{slug:'automation-in-it-operations'},update:{},create:{title:'Automation in IT Operations',slug:'automation-in-it-operations',excerpt:'How automation can reduce repetitive infrastructure operations.',content:'Using automation platforms and scripts to improve IT operations, monitoring and workflows.',category:'Automation',tags:'Automation, n8n, DevOps, IT'}});
 const settings: Array<[string,string]> = [['site_name','SHAHUL.ONLINE'],['site_title','Shahul Hameed | Senior Infrastructure Engineer'],['hero_badge','SYSTEM ONLINE • OPEN TO OPPORTUNITIES'],['hero_title','Building secure digital infrastructure.'],['hero_description','I’m Shahul Hameed — an IT Infrastructure and Cybersecurity professional focused on enterprise networking, cloud, automation and future technology.'],['hero_photo','/shahul-server-room.webp'],['hero_mission','Design secure systems. Automate operations. Build what’s next.'],['experience_years','12+'],['primary_cert','CCNP'],['about_text','I work across enterprise IT infrastructure, networking, Windows environments, cloud platforms, security and business automation.'],['contact_email','admin@shahul.online'],['contact_phone',''],['linkedin_url',''],['github_url',''],['whatsapp_url','']];
 for(const [key,value] of settings) await db.setting.upsert({where:{key},update:{value},create:{key,value}});
 const services: Array<[string,string,string,number]> = [['Infrastructure & Networking','Network design, routing, switching, VPN, troubleshooting and infrastructure operations.','network',0],['Cybersecurity','Security hardening, firewalls, access control, monitoring and practical defense.','shield',1],['Cloud & Systems','Cloud architecture, Windows/Linux systems, virtualization and migration planning.','cloud',2],['Automation & AI','Business automation, n8n workflows, APIs and AI-assisted operational systems.','workflow',3]];
 for(const [title,description,icon,sortOrder] of services){const id=Number(sortOrder)+1;await db.service.upsert({where:{id},update:{title,description,icon,sortOrder,published:true},create:{id,title,description,icon,sortOrder,published:true}})}
 const innovations: Array<[string,string,string,number]> = [['AI Agents','Autonomous assistants for business operations, research and technical workflows.','brain',0],['Smart Infrastructure','Connected infrastructure using IoT, monitoring and intelligent automation.','radio',1],['AI + Real Estate','Smarter property workflows, lead intelligence and customer experience.','home',2],['Automation Lab','n8n, APIs and event-driven automation to eliminate repetitive work.','workflow',3],['Cyber Defense','Practical security monitoring, hardening and incident response concepts.','bot',4],['Smart Energy','IoT-powered energy monitoring, analytics and optimization.','sun',5]];
 for(const [title,description,icon,sortOrder] of innovations){const id=Number(sortOrder)+1;await db.innovationItem.upsert({where:{id},update:{title,description,icon,sortOrder,published:true},create:{id,title,description,icon,sortOrder,published:true}})}

 const homepage: Array<[string,string,string,string,string,number]> = [
  ['about','PROFILE','Senior Infrastructure Engineer','Infrastructure, cybersecurity and cloud engineering.','I design and operate secure, scalable technology environments across networking, Windows, cloud, virtualization and automation.',0],
  ['case-studies','ENGINEERING METHOD','From problem to production','Case-study driven engineering','Explore the architecture, implementation approach and outcomes behind selected projects.',1],
  ['contact-cta','NEXT MISSION','Let’s build what’s next','Have a technology challenge?','Let’s discuss infrastructure, cybersecurity, automation or a new digital product.',2]
 ];
 for(const [sectionKey,eyebrow,title,subtitle,content,sortOrder] of homepage){await db.homepageSection.upsert({where:{sectionKey:String(sectionKey)},update:{eyebrow:String(eyebrow),title:String(title),subtitle:String(subtitle),content:String(content),sortOrder:Number(sortOrder),published:true},create:{sectionKey:String(sectionKey),eyebrow:String(eyebrow),title:String(title),subtitle:String(subtitle),content:String(content),sortOrder:Number(sortOrder),published:true}})}
 const seo: Array<[string,string,string,string]> = [
  ['home','Shahul Hameed | Senior Infrastructure Engineer','IT Infrastructure, Networking, Cybersecurity, Cloud, Automation and AI professional portfolio.','Senior Infrastructure Engineer, IT Infrastructure, Cisco, Cybersecurity, Cloud, Windows Server, Automation'],
  ['projects','Projects | Shahul.online','Infrastructure, cybersecurity, automation, IoT and AI engineering projects.','IT projects, network infrastructure, cybersecurity projects, automation'],
  ['certifications','Certifications | Shahul.online','Professional certifications, education and capability records.','CCNP, Cyber Forensics, Information Security, Certifications']
 ];
 for(const [pageKey,title,description,keywords] of seo){await db.seoPage.upsert({where:{pageKey:String(pageKey)},update:{title:String(title),description:String(description),keywords:String(keywords)},create:{pageKey:String(pageKey),title:String(title),description:String(description),keywords:String(keywords)}})}
 console.log('Database seed completed successfully.');
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>db.$disconnect());
